### ISSUE TITLE
Can I add rose-pine to google collab?

### ISSUE THREAD

**Issue by benthecoder** [h4pZ/rose-pine-matplotlib#1]
Hi there, not really an issue but a question. I was wondering if it's possible to implement this theme on google collab. I can't figure out how to do step 2, which is adding it to mpl_configdir/stylelib. 

Thank you.

**Comment by h4pZ** [comment]
Hi,

Yes you can use it on colab too. Just get the file for the style you want to use on colab by uploading it or using wget (`!wget https://raw.githubusercontent.com/h4pZ/rose-pine-matplotlib/main/themes/rose-pine.mplstyle`) and then when setting the style with matplotlib just put the path of the file like `plt.style.use("path_to_file")`.

Or you could move the file to `/root/.config/matplotlib/stylelib/` and call it just by the name.

Example:

![Example](https://i.imgur.com/XuP7mnX.png)

**Comment by benthecoder** [comment]
Thanks so much! Awesome theme by the way!

**Comment by benthecoder** [comment]
![Screenshot 2021-05-10 at 1 27 30 AM](https://user-images.githubusercontent.com/49143413/117581348-e4ca3080-b12e-11eb-8e9f-270315298572.png)

Hi sorry but Is there an issue on my part for why I'm getting a white part around the graph?

**Comment by h4pZ** [comment]
Are you using the exact same code as in the example? or are you using another library that relies on matplotlib like seaborn? If so try setting `plt.style.use` on a call after calling all the imports.
